name: Build Debian Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Add workflow_dispatch trigger
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential debhelper
    - name:  build-deb-action
      uses: jiro4989/build-deb-action@v2
      with:
        # Package name of debian package.
        package: libmodbus
        # Directory of release files.
        package_root: ./
        # Package maintainer name.
        maintainer: Aleksandr Makarov <aleksandr.o.makarov@gmail.com>
        # Package version.
        version: 0.1

    - name: Publish artifact
      uses: actions/upload-artifact@v2
      with:
        name: libmodbus-deb
        path: ./*.deb
